server:
  port: 8080

spring:
  config:
    import:
      - application-db.yml
      - application-jwt.yml

mybatis:
  type-aliases-package: com.otclub.humate.domain
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# log4jdbc, Mybatis Console Log
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: OFF     #SQL만 로그로 남긴다.
      sqltiming: INFO    #SQL과 소요시간을 표기한다.
      connection : OFF  # 커넥션 확인가능
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE