server:
  port: 8080

spring:
  config:
    import: application-db.yml

mybatis:
  type-aliases-package: com.otclub.humate.domain
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true